Harness IO Git Sync. MODIFY: Setup/Applications/Fundamentals Harness training/Workflows/Rolling test.yaml

diff --git a/Setup/Applications/Fundamentals Harness training/Workflows/Rolling test.yaml b/Setup/Applications/Fundamentals Harness training/Workflows/Rolling test.yaml
--- a/Setup/Applications/Fundamentals Harness training/Workflows/Rolling test.yaml
+++ b/Setup/Applications/Fundamentals Harness training/Workflows/Rolling test.yaml
@@ -41,11 +41,32 @@ phases:
         includeInfraSelectors: true
         outputVars: CONTINUE
         publishAsVar: true
-        scriptString: |2-
+        scriptString: |-
+          # Fetch verison number from app login page
+          appVersion='dummy'
 
-          CONTINUE=1
+          if [ "$appVersion" == "" ]; then
+            echo "Unable to obtain application version"
+            exit 1
+          elif [[ "$appVersion" =~ "503" ]]; then
+            currentHour=`date +%H`
+            if [[ $currentHour =~ "" ]]; then
+              echo "The application is not currently available. It's past $currentHour':00', it is probably offline"
+              CONTINUE=0
+            else
+              echo "The application is not currently available, or it might be overloaded, please investigate"
+              CONTINUE=0
+            fi
+          fi
 
-          export CONTINUE
+          # If the versions don't match, we don't want to continue
+          if [ "dummy" != "$appVersion" ]; then
+            echo "App version $appVersion doesn't match Admin app version ${adminAppVersion}"
+            CONTINUE=0
+          else
+            echo "The application version $appVersion matches the Admin app version ${adminAppVersion}, continuing..."
+            CONTINUE=1
+          fi
         scriptType: BASH
         secretOutputVars: ''
         sshKeyRefName: null
